Repository pacollins/hugo-future-imperfect-slim, pull requests merged in 2019-08, with the labels that each got.

#43 Improved French translation
  exampleSite/content/about/_index.fr.md
  exampleSite/content/contact/_index.fr.md
  i18n/fr.toml
Labels: Type: Enhancement

#44 Added Chinese translations
  i18n/zh-CN.toml
  i18n/zh-TW.toml
Labels: Status: Accepted, Type: Enhancement

#50 micro fix - typo (parameter)
  README.md
Labels: Status: Completed

#48 Git ignore exampleSite/public
  .gitignore
Labels: Status: Accepted

#49 Added back CC-BY 3.0 to original theme
  LICENSE.md
Labels: Priority: Critical, Status: Review Needed

#45 Revert to ReCAPTCHA 2 for Staticman
  exampleSite/config.toml
  layouts/partials/head.html
  layouts/post/comments.html
  layouts/post/content-single.html
  layouts/post/staticman.html
  static/css/main.min.css
  static/css/main.scss
Labels: Status: Review Needed, Type: Bug

#58 Code cleanup
  .github/CONTRIBUTING.md
  exampleSite/content/blog/creating-a-new-theme.br.md
  exampleSite/content/blog/creating-a-new-theme.fr.md
  exampleSite/content/blog/creating-a-new-theme.md
  exampleSite/content/blog/creating-a-new-theme.pl.md
  static/js/main.js
  static/js/util.js
Labels: Status: Completed, Type: Maintenance

#60 Fixes comments.html to respect the staticman boolean in [params.staticman]
  exampleSite/config.toml
  layouts/post/comments.html
  layouts/post/staticman.html
Labels: Status: Completed, Type: Bug

#51 Added license URI to orignal author
  LICENSE.md
  README.md
  i18n/br.toml
  i18n/en.toml
  i18n/fr.toml
  i18n/pl.toml
  i18n/zh-CN.toml
  i18n/zh-TW.toml
  layouts/partials/site-footer.html
Labels: Priority: Critical, Status: Accepted, Type: Maintenance

#52 Added es.toml
  i18n/es.toml
Labels: Status: Accepted, Type: Enhancement

#71 Fixed Hugo 0.57 breaking change
  exampleSite/config.toml
  layouts/_default/list.html
Labels: Priority: Critical, Status: Review Needed, Type: Bug, Type: Maintenance

#73 Fix 404.html with locales
  i18n/br.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/pl.toml
  i18n/zh-CN.toml
  i18n/zh-TW.toml
  layouts/404.html
Labels: Status: Review Needed, Type: Bug

#77 Separated CSS styles from 404.html
  layouts/404.html
  static/css/404.css
Labels: Type: Enhancement

#69 Staticman nested comments support from Huginn
  assets/js/staticman.js
  assets/scss/main.scss
  exampleSite/config.toml
  exampleSite/resources/_gen/assets/js/js/staticman.js_8cd1ffcbd6280a9d3369580fb528eb22.content
  exampleSite/resources/_gen/assets/js/js/staticman.js_8cd1ffcbd6280a9d3369580fb528eb22.json
  exampleSite/resources/_gen/assets/scss/scss/main.scss_b5a97001882d870cddf46d3bce56b70e.content
  exampleSite/resources/_gen/assets/scss/scss/main.scss_b5a97001882d870cddf46d3bce56b70e.json
  exampleSite/staticman.yml
  i18n/br.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/pl.toml
  i18n/zh-CN.toml
  i18n/zh-TW.toml
  layouts/partials/head.html
  layouts/partials/scripts.html
  layouts/post/staticman.html
Labels: Type: Bug, Type: Enhancement

#78 Allow logos in nav-title
  assets/scss/main.min.css
  assets/scss/main.scss
  layouts/partials/site-header.html
Labels: Status: Review Needed, Type: Enhancement

#81 Updated README to link to Staticman Wiki
  README.md
Labels: Status: Review Needed, Type: Enhancement, Type: Maintenance

#80 ⚑ → Language list
  assets/scss/main.min.css
  assets/scss/main.scss
  exampleSite/config.toml
  exampleSite/resources/_gen/assets/scss/scss/main.scss_b5a97001882d870cddf46d3bce56b70e.content
  exampleSite/resources/_gen/assets/scss/scss/main.scss_b5a97001882d870cddf46d3bce56b70e.json
  layouts/partials/head.html
  layouts/partials/language-menu.html
  layouts/partials/site-header.html
  layouts/partials/site-intro.html
Labels: Type: Bug, Type: Enhancement

#83 Updated Menu Syntax to suit Hugo Docs
  exampleSite/config.toml
  layouts/partials/site-header.html
Labels: Status: Review Needed, Type: Enhancement, Type: Maintenance

#72 Fix Twitter card and move to `images` instead of `featured`
  archetypes/blog.md
  archetypes/default.md
  archetypes/itemized.md
  layouts/partials/meta.html
  layouts/post/featured.html
Labels: Type: Bug, Type: Enhancement
