Repository pacollins/hugo-future-imperfect-slim, pull requests merged in 2019-10, with the labels that each got.

#94 Fix Long Title Text
  assets/scss/main.scss
  layouts/post/pagination.html
Labels: Status: In Progress, Status: Review Needed, Type: Bug

#97 Fix wrong author
  layouts/partials/head.html
Labels: Status: Accepted, Type: Bug

#98 Fixed sentence more match zh_TW language
  i18n/zh-TW.toml
Labels: Status: Review Needed, Type: Maintenance
