Repository pacollins/hugo-future-imperfect-slim, pull requests merged in 2019-07, with the labels that each got.

#31 Enable custom Staticman endpoint
  exampleSite/config.toml
  layouts/post/staticman.html
Labels: Status: Accepted, Type: Maintenance

#33 Fix img path for baseurl with subdirectory
  layouts/post/featured.html
  static/css/main.min.css
  static/css/main.scss
Labels: Status: Accepted, Type: Bug

#22 Disable recent posts when set 0
  layouts/partials/site-sidebar.html
Labels: Status: Accepted, Type: Bug

#36 Prevent adblocking of social icons
  layouts/partials/site-footer.html
  layouts/partials/site-intro.html
  layouts/partials/socnet-icon.html
  layouts/post/content-single.html
  static/css/main.min.css
  static/css/main.scss
Labels: Status: Review Needed, Type: Bug
