Repository pacollins/hugo-future-imperfect-slim, pull requests merged in 2019-06, with the labels that each got.

#14 Bug fix: social share links (#5)
  exampleSite/config.toml
  layouts/partials/head.html
  layouts/partials/share-buttons.html
Labels: Status: Accepted, Type: Bug

#16 Include Brazilian portuguese
  README.md
  exampleSite/config.toml
  exampleSite/content/about/_index.br.md
  exampleSite/content/blog/creating-a-new-theme.br.md
  exampleSite/content/contact/_index.br.md
  i18n/br.toml
  layouts/contact/list.html
Labels: Status: Accepted, Type: Enhancement

#27 Add other social icon #26
  exampleSite/config.toml
  layouts/partials/head.html
  layouts/partials/social-icon.html
Labels: Status: Accepted, Type: Maintenance

#25 Bug Fix: Fix non-date image path
  layouts/post/featured.html
Labels: Status: Review Needed, Type: Bug
