Repository pacollins/hugo-future-imperfect-slim, pull requests merged in 2020-03, with the labels that each got.

#108 Allow and configure hiding the intro on mobile pages
  assets/scss/main.scss
  exampleSite/config.toml
  layouts/partials/site-intro.html
Labels: Status: Review Needed, Type: Enhancement

#123 Adjust exampleSite directories
  exampleSite/static/css/add-on.css
  exampleSite/static/js/add-on.js
Labels: Status: Accepted, Type: Bug

#122 Address edge cases around multiple content types
  archetypes/default.md
  exampleSite/config.toml
  exampleSite/content/blog/emoji-support.fr.md
  exampleSite/content/blog/emoji-support.md
  exampleSite/content/blog/markdown-syntax.fr.md
  exampleSite/content/blog/markdown-syntax.md
  exampleSite/content/blog/placeholder-text.md
  exampleSite/content/blog/rich-content.md
  layouts/_default/comments.html
  layouts/_default/content-list.html
  layouts/_default/content-single.html
  layouts/_default/featured.html
  layouts/_default/header.html
  layouts/_default/index.html
  layouts/_default/list.html
  layouts/_default/pagination.html
  layouts/_default/single.html
  layouts/_default/staticman.html
  layouts/_default/stats.html
  layouts/post/header.html
  layouts/taxonomy/category.html
  layouts/taxonomy/tag.html
Labels: Status: Review Needed, Type: Bug

#127 Add email translation
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/ja.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/zh-CN.toml
  i18n/zh-TW.toml
  layouts/partials/share-buttons.html
Labels: Status: Accepted, Type: Bug
